"""
Global configuration for the FDKD Demo Backend.

Supports both local and Colab environments:
  - Local: checkpoints in <project_root>/checkpoints/
  - Colab: checkpoints in /content/drive/MyDrive/checkpoints
  - Override: FDKD_CHECKPOINT_DIR environment variable
"""
import os
import torch

# Device
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Dataset
NUM_CLASSES = 200

# ── Checkpoint path auto-detection ──
# Priority: env var > local checkpoints/ > Colab default
_PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
_LOCAL_CKPT = os.path.join(_PROJECT_ROOT, "checkpoints")
_COLAB_CKPT = "/content/drive/MyDrive/checkpoints"

def _detect_checkpoint_dir() -> str:
    """Auto-detect checkpoint directory based on environment."""
    # 1. Explicit override via env var
    env_dir = os.environ.get("FDKD_CHECKPOINT_DIR")
    if env_dir:
        return env_dir
    # 2. Local checkpoints directory
    if os.path.isdir(_LOCAL_CKPT):
        return _LOCAL_CKPT
    # 3. Colab default
    if os.path.isdir(_COLAB_CKPT):
        return _COLAB_CKPT
    # 4. Fallback to local (will be created if needed)
    return _LOCAL_CKPT

CHECKPOINT_DIR = _detect_checkpoint_dir()

# Runtime mode detection
IS_COLAB = os.path.exists("/content") and os.path.isdir("/content")

# FDKD pipeline checkpoint mapping (directory name → model role)
# Priority order: first match wins
# *_clean variants are auto-generated by preprocess_checkpoints() —
# they contain pre-extracted student weights without architecture.* prefix.
TEACHER_DIRS = ["swinb_fully", "swinbase_fully"]
ASSISTANT_DIRS = [
    "swinb_r18_clean", "dkd_swinb_r18_clean",          # direct DKD from Swin-B
    "swinb_r18", "dkd_swinb_r18",                       # raw distillation
]
STUDENT_DIRS = [
    "r18_fully",                                        # fully trained baseline
]

# Checkpoint file extensions to search for
CHECKPOINT_EXTENSIONS = ('.pth', '.pt', '.pkl', '.bin', '.ckpt', '.pth.tar')

# Image preprocessing
IMAGE_SIZE = 224
IMAGENET_MEAN = [0.485, 0.456, 0.406]
IMAGENET_STD = [0.229, 0.224, 0.225]

# Model metadata (shared by pipeline, metrics display, etc.)
MODEL_INFO = {
    "teacher":   {"name": "Swin-B",        "params": "86.95M", "gflops": "15,467"},
    "assistant": {"name": "ResNet-18 (DKD)","params": "11.28M", "gflops": "1,819"},
    "student":   {"name": "ResNet-18 (Baseline)","params": "11.28M", "gflops": "1,819"},
}

MODEL_ROLES = ["teacher", "assistant", "student"]

# ngrok (Colab only)
NGROK_AUTH_TOKEN = os.environ.get("NGROK_AUTH_TOKEN", "")
